"use client";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "antd/dist/reset.css";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Layout } from "antd";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  if (pathname === "/" || pathname === "/login" || pathname === "/register") {
    return (
      <html lang="en">
        <body className={inter.className}>
          <AntdRegistry>
            <Layout>{children}</Layout>
          </AntdRegistry>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Layout>
            <Navbar isHeader={true} />
            {children}
            {/* <Navbar /> // why is Navbar at the bottom again? */}
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
